### ISSUE TITLE
eth_compileSolidity does not exist

### ISSUE THREAD

**Issue by dilumn** [DigixGlobal/ethereum-ruby#19]
Seems like `client.compile_solidity` is not working. Do you have any work around for this??
 ```
client.compile_solidity("SimpleNameRegistry.sol")
 => {"jsonrpc"=>"2.0", "id"=>5, "error"=>{"code"=>-32601, "message"=>"The method 
eth_compileSolidity does not exist/is not available"}} 
```

**Comment by ayrat555** [comment]
@dilumn This command is removed from geth

https://github.com/ethereum/go-ethereum/issues/3793

**Comment by litch** [comment]
I noticed this was removed from geth, which is problematic.  Is this library now unusable then for working with contracts?  Since the only documented way of working with an existing contract was to use the initializer to compile it, etc?

I don't think that this issue should be closed unless this project's README functions again.
